// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: developer.proto

package com.test.proto;

public interface DeveloperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.proto.Developer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string position = 4;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>optional string position = 4;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
