// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: developer.proto

package com.test.proto;

public interface DeveloperListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.proto.DeveloperList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.test.proto.Developer developers = 1;</code>
   */
  java.util.List<com.test.proto.Developer> 
      getDevelopersList();
  /**
   * <code>repeated .com.test.proto.Developer developers = 1;</code>
   */
  com.test.proto.Developer getDevelopers(int index);
  /**
   * <code>repeated .com.test.proto.Developer developers = 1;</code>
   */
  int getDevelopersCount();
  /**
   * <code>repeated .com.test.proto.Developer developers = 1;</code>
   */
  java.util.List<? extends com.test.proto.DeveloperOrBuilder> 
      getDevelopersOrBuilderList();
  /**
   * <code>repeated .com.test.proto.Developer developers = 1;</code>
   */
  com.test.proto.DeveloperOrBuilder getDevelopersOrBuilder(
      int index);
}
