// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: developer.proto

package com.test.proto;

public final class DeveloperProtos {
  private DeveloperProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_proto_Developer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_proto_Developer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_proto_DeveloperList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_proto_DeveloperList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017developer.proto\022\016com.test.proto\"F\n\tDev" +
      "eloper\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005emai" +
      "l\030\003 \001(\t\022\020\n\010position\030\004 \001(\t\">\n\rDeveloperLi" +
      "st\022-\n\ndevelopers\030\001 \003(\0132\031.com.test.proto." +
      "DeveloperB#\n\016com.test.protoB\017DeveloperPr" +
      "otosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test_proto_Developer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_proto_Developer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_proto_Developer_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Position", });
    internal_static_com_test_proto_DeveloperList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_proto_DeveloperList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_proto_DeveloperList_descriptor,
        new java.lang.String[] { "Developers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
