// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: software.proto

package com.test.proto;

public final class SoftwareProtos {
  private SoftwareProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_proto_Software_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_proto_Software_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_proto_SoftwareList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_proto_SoftwareList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016software.proto\022\016com.test.proto\032\017develo" +
      "per.proto\"S\n\010Software\022\014\n\004name\030\001 \001(\t\022\n\n\002i" +
      "d\030\002 \001(\005\022-\n\ndevelopers\030\003 \003(\0132\031.com.test.p" +
      "roto.Developer\";\n\014SoftwareList\022+\n\tsoftwa" +
      "res\030\001 \003(\0132\030.com.test.proto.SoftwareB\"\n\016c" +
      "om.test.protoB\016SoftwareProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.test.proto.DeveloperProtos.getDescriptor(),
        }, assigner);
    internal_static_com_test_proto_Software_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_proto_Software_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_proto_Software_descriptor,
        new java.lang.String[] { "Name", "Id", "Developers", });
    internal_static_com_test_proto_SoftwareList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_proto_SoftwareList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_proto_SoftwareList_descriptor,
        new java.lang.String[] { "Softwares", });
    com.test.proto.DeveloperProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
