// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: software.proto

package com.test.proto;

/**
 * Protobuf type {@code com.test.proto.SoftwareList}
 */
public  final class SoftwareList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.test.proto.SoftwareList)
    SoftwareListOrBuilder {
  // Use SoftwareList.newBuilder() to construct.
  private SoftwareList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SoftwareList() {
    softwares_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SoftwareList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              softwares_ = new java.util.ArrayList<com.test.proto.Software>();
              mutable_bitField0_ |= 0x00000001;
            }
            softwares_.add(
                input.readMessage(com.test.proto.Software.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        softwares_ = java.util.Collections.unmodifiableList(softwares_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.proto.SoftwareProtos.internal_static_com_test_proto_SoftwareList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.proto.SoftwareProtos.internal_static_com_test_proto_SoftwareList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.proto.SoftwareList.class, com.test.proto.SoftwareList.Builder.class);
  }

  public static final int SOFTWARES_FIELD_NUMBER = 1;
  private java.util.List<com.test.proto.Software> softwares_;
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  public java.util.List<com.test.proto.Software> getSoftwaresList() {
    return softwares_;
  }
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  public java.util.List<? extends com.test.proto.SoftwareOrBuilder> 
      getSoftwaresOrBuilderList() {
    return softwares_;
  }
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  public int getSoftwaresCount() {
    return softwares_.size();
  }
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  public com.test.proto.Software getSoftwares(int index) {
    return softwares_.get(index);
  }
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  public com.test.proto.SoftwareOrBuilder getSoftwaresOrBuilder(
      int index) {
    return softwares_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < softwares_.size(); i++) {
      output.writeMessage(1, softwares_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < softwares_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, softwares_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.proto.SoftwareList)) {
      return super.equals(obj);
    }
    com.test.proto.SoftwareList other = (com.test.proto.SoftwareList) obj;

    boolean result = true;
    result = result && getSoftwaresList()
        .equals(other.getSoftwaresList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSoftwaresCount() > 0) {
      hash = (37 * hash) + SOFTWARES_FIELD_NUMBER;
      hash = (53 * hash) + getSoftwaresList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.proto.SoftwareList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.proto.SoftwareList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.proto.SoftwareList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.proto.SoftwareList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.proto.SoftwareList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.proto.SoftwareList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.proto.SoftwareList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.proto.SoftwareList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.proto.SoftwareList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.proto.SoftwareList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.proto.SoftwareList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.test.proto.SoftwareList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.test.proto.SoftwareList)
      com.test.proto.SoftwareListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_SoftwareList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_SoftwareList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.SoftwareList.class, com.test.proto.SoftwareList.Builder.class);
    }

    // Construct using com.test.proto.SoftwareList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSoftwaresFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (softwaresBuilder_ == null) {
        softwares_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        softwaresBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_SoftwareList_descriptor;
    }

    public com.test.proto.SoftwareList getDefaultInstanceForType() {
      return com.test.proto.SoftwareList.getDefaultInstance();
    }

    public com.test.proto.SoftwareList build() {
      com.test.proto.SoftwareList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.proto.SoftwareList buildPartial() {
      com.test.proto.SoftwareList result = new com.test.proto.SoftwareList(this);
      int from_bitField0_ = bitField0_;
      if (softwaresBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          softwares_ = java.util.Collections.unmodifiableList(softwares_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.softwares_ = softwares_;
      } else {
        result.softwares_ = softwaresBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.proto.SoftwareList) {
        return mergeFrom((com.test.proto.SoftwareList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.proto.SoftwareList other) {
      if (other == com.test.proto.SoftwareList.getDefaultInstance()) return this;
      if (softwaresBuilder_ == null) {
        if (!other.softwares_.isEmpty()) {
          if (softwares_.isEmpty()) {
            softwares_ = other.softwares_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSoftwaresIsMutable();
            softwares_.addAll(other.softwares_);
          }
          onChanged();
        }
      } else {
        if (!other.softwares_.isEmpty()) {
          if (softwaresBuilder_.isEmpty()) {
            softwaresBuilder_.dispose();
            softwaresBuilder_ = null;
            softwares_ = other.softwares_;
            bitField0_ = (bitField0_ & ~0x00000001);
            softwaresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSoftwaresFieldBuilder() : null;
          } else {
            softwaresBuilder_.addAllMessages(other.softwares_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.proto.SoftwareList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.proto.SoftwareList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.test.proto.Software> softwares_ =
      java.util.Collections.emptyList();
    private void ensureSoftwaresIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        softwares_ = new java.util.ArrayList<com.test.proto.Software>(softwares_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.proto.Software, com.test.proto.Software.Builder, com.test.proto.SoftwareOrBuilder> softwaresBuilder_;

    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public java.util.List<com.test.proto.Software> getSoftwaresList() {
      if (softwaresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(softwares_);
      } else {
        return softwaresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public int getSoftwaresCount() {
      if (softwaresBuilder_ == null) {
        return softwares_.size();
      } else {
        return softwaresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public com.test.proto.Software getSoftwares(int index) {
      if (softwaresBuilder_ == null) {
        return softwares_.get(index);
      } else {
        return softwaresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder setSoftwares(
        int index, com.test.proto.Software value) {
      if (softwaresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSoftwaresIsMutable();
        softwares_.set(index, value);
        onChanged();
      } else {
        softwaresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder setSoftwares(
        int index, com.test.proto.Software.Builder builderForValue) {
      if (softwaresBuilder_ == null) {
        ensureSoftwaresIsMutable();
        softwares_.set(index, builderForValue.build());
        onChanged();
      } else {
        softwaresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder addSoftwares(com.test.proto.Software value) {
      if (softwaresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSoftwaresIsMutable();
        softwares_.add(value);
        onChanged();
      } else {
        softwaresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder addSoftwares(
        int index, com.test.proto.Software value) {
      if (softwaresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSoftwaresIsMutable();
        softwares_.add(index, value);
        onChanged();
      } else {
        softwaresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder addSoftwares(
        com.test.proto.Software.Builder builderForValue) {
      if (softwaresBuilder_ == null) {
        ensureSoftwaresIsMutable();
        softwares_.add(builderForValue.build());
        onChanged();
      } else {
        softwaresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder addSoftwares(
        int index, com.test.proto.Software.Builder builderForValue) {
      if (softwaresBuilder_ == null) {
        ensureSoftwaresIsMutable();
        softwares_.add(index, builderForValue.build());
        onChanged();
      } else {
        softwaresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder addAllSoftwares(
        java.lang.Iterable<? extends com.test.proto.Software> values) {
      if (softwaresBuilder_ == null) {
        ensureSoftwaresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, softwares_);
        onChanged();
      } else {
        softwaresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder clearSoftwares() {
      if (softwaresBuilder_ == null) {
        softwares_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        softwaresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public Builder removeSoftwares(int index) {
      if (softwaresBuilder_ == null) {
        ensureSoftwaresIsMutable();
        softwares_.remove(index);
        onChanged();
      } else {
        softwaresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public com.test.proto.Software.Builder getSoftwaresBuilder(
        int index) {
      return getSoftwaresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public com.test.proto.SoftwareOrBuilder getSoftwaresOrBuilder(
        int index) {
      if (softwaresBuilder_ == null) {
        return softwares_.get(index);  } else {
        return softwaresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public java.util.List<? extends com.test.proto.SoftwareOrBuilder> 
         getSoftwaresOrBuilderList() {
      if (softwaresBuilder_ != null) {
        return softwaresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(softwares_);
      }
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public com.test.proto.Software.Builder addSoftwaresBuilder() {
      return getSoftwaresFieldBuilder().addBuilder(
          com.test.proto.Software.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public com.test.proto.Software.Builder addSoftwaresBuilder(
        int index) {
      return getSoftwaresFieldBuilder().addBuilder(
          index, com.test.proto.Software.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.proto.Software softwares = 1;</code>
     */
    public java.util.List<com.test.proto.Software.Builder> 
         getSoftwaresBuilderList() {
      return getSoftwaresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.proto.Software, com.test.proto.Software.Builder, com.test.proto.SoftwareOrBuilder> 
        getSoftwaresFieldBuilder() {
      if (softwaresBuilder_ == null) {
        softwaresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.proto.Software, com.test.proto.Software.Builder, com.test.proto.SoftwareOrBuilder>(
                softwares_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        softwares_ = null;
      }
      return softwaresBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.test.proto.SoftwareList)
  }

  // @@protoc_insertion_point(class_scope:com.test.proto.SoftwareList)
  private static final com.test.proto.SoftwareList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.proto.SoftwareList();
  }

  public static com.test.proto.SoftwareList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SoftwareList>
      PARSER = new com.google.protobuf.AbstractParser<SoftwareList>() {
    public SoftwareList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SoftwareList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SoftwareList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SoftwareList> getParserForType() {
    return PARSER;
  }

  public com.test.proto.SoftwareList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

