// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: software.proto

package com.test.proto;

/**
 * Protobuf type {@code com.test.proto.Software}
 */
public  final class Software extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.test.proto.Software)
    SoftwareOrBuilder {
  // Use Software.newBuilder() to construct.
  private Software(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Software() {
    name_ = "";
    id_ = 0;
    developers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Software(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            id_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              developers_ = new java.util.ArrayList<com.test.proto.Developer>();
              mutable_bitField0_ |= 0x00000004;
            }
            developers_.add(
                input.readMessage(com.test.proto.Developer.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        developers_ = java.util.Collections.unmodifiableList(developers_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.proto.SoftwareProtos.internal_static_com_test_proto_Software_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.proto.SoftwareProtos.internal_static_com_test_proto_Software_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.proto.Software.class, com.test.proto.Software.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>optional int32 id = 2;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int DEVELOPERS_FIELD_NUMBER = 3;
  private java.util.List<com.test.proto.Developer> developers_;
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  public java.util.List<com.test.proto.Developer> getDevelopersList() {
    return developers_;
  }
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  public java.util.List<? extends com.test.proto.DeveloperOrBuilder> 
      getDevelopersOrBuilderList() {
    return developers_;
  }
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  public int getDevelopersCount() {
    return developers_.size();
  }
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  public com.test.proto.Developer getDevelopers(int index) {
    return developers_.get(index);
  }
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  public com.test.proto.DeveloperOrBuilder getDevelopersOrBuilder(
      int index) {
    return developers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    for (int i = 0; i < developers_.size(); i++) {
      output.writeMessage(3, developers_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    for (int i = 0; i < developers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, developers_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.proto.Software)) {
      return super.equals(obj);
    }
    com.test.proto.Software other = (com.test.proto.Software) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getId()
        == other.getId());
    result = result && getDevelopersList()
        .equals(other.getDevelopersList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (getDevelopersCount() > 0) {
      hash = (37 * hash) + DEVELOPERS_FIELD_NUMBER;
      hash = (53 * hash) + getDevelopersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.proto.Software parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.proto.Software parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.proto.Software parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.proto.Software parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.proto.Software parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.proto.Software parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.proto.Software parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.proto.Software parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.proto.Software parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.proto.Software parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.proto.Software prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.test.proto.Software}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.test.proto.Software)
      com.test.proto.SoftwareOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_Software_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_Software_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.Software.class, com.test.proto.Software.Builder.class);
    }

    // Construct using com.test.proto.Software.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDevelopersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      id_ = 0;

      if (developersBuilder_ == null) {
        developers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        developersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.proto.SoftwareProtos.internal_static_com_test_proto_Software_descriptor;
    }

    public com.test.proto.Software getDefaultInstanceForType() {
      return com.test.proto.Software.getDefaultInstance();
    }

    public com.test.proto.Software build() {
      com.test.proto.Software result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.proto.Software buildPartial() {
      com.test.proto.Software result = new com.test.proto.Software(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.id_ = id_;
      if (developersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          developers_ = java.util.Collections.unmodifiableList(developers_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.developers_ = developers_;
      } else {
        result.developers_ = developersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.proto.Software) {
        return mergeFrom((com.test.proto.Software)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.proto.Software other) {
      if (other == com.test.proto.Software.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (developersBuilder_ == null) {
        if (!other.developers_.isEmpty()) {
          if (developers_.isEmpty()) {
            developers_ = other.developers_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDevelopersIsMutable();
            developers_.addAll(other.developers_);
          }
          onChanged();
        }
      } else {
        if (!other.developers_.isEmpty()) {
          if (developersBuilder_.isEmpty()) {
            developersBuilder_.dispose();
            developersBuilder_ = null;
            developers_ = other.developers_;
            bitField0_ = (bitField0_ & ~0x00000004);
            developersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDevelopersFieldBuilder() : null;
          } else {
            developersBuilder_.addAllMessages(other.developers_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.proto.Software parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.proto.Software) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.test.proto.Developer> developers_ =
      java.util.Collections.emptyList();
    private void ensureDevelopersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        developers_ = new java.util.ArrayList<com.test.proto.Developer>(developers_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.proto.Developer, com.test.proto.Developer.Builder, com.test.proto.DeveloperOrBuilder> developersBuilder_;

    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public java.util.List<com.test.proto.Developer> getDevelopersList() {
      if (developersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(developers_);
      } else {
        return developersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public int getDevelopersCount() {
      if (developersBuilder_ == null) {
        return developers_.size();
      } else {
        return developersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public com.test.proto.Developer getDevelopers(int index) {
      if (developersBuilder_ == null) {
        return developers_.get(index);
      } else {
        return developersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder setDevelopers(
        int index, com.test.proto.Developer value) {
      if (developersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDevelopersIsMutable();
        developers_.set(index, value);
        onChanged();
      } else {
        developersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder setDevelopers(
        int index, com.test.proto.Developer.Builder builderForValue) {
      if (developersBuilder_ == null) {
        ensureDevelopersIsMutable();
        developers_.set(index, builderForValue.build());
        onChanged();
      } else {
        developersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder addDevelopers(com.test.proto.Developer value) {
      if (developersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDevelopersIsMutable();
        developers_.add(value);
        onChanged();
      } else {
        developersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder addDevelopers(
        int index, com.test.proto.Developer value) {
      if (developersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDevelopersIsMutable();
        developers_.add(index, value);
        onChanged();
      } else {
        developersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder addDevelopers(
        com.test.proto.Developer.Builder builderForValue) {
      if (developersBuilder_ == null) {
        ensureDevelopersIsMutable();
        developers_.add(builderForValue.build());
        onChanged();
      } else {
        developersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder addDevelopers(
        int index, com.test.proto.Developer.Builder builderForValue) {
      if (developersBuilder_ == null) {
        ensureDevelopersIsMutable();
        developers_.add(index, builderForValue.build());
        onChanged();
      } else {
        developersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder addAllDevelopers(
        java.lang.Iterable<? extends com.test.proto.Developer> values) {
      if (developersBuilder_ == null) {
        ensureDevelopersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, developers_);
        onChanged();
      } else {
        developersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder clearDevelopers() {
      if (developersBuilder_ == null) {
        developers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        developersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public Builder removeDevelopers(int index) {
      if (developersBuilder_ == null) {
        ensureDevelopersIsMutable();
        developers_.remove(index);
        onChanged();
      } else {
        developersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public com.test.proto.Developer.Builder getDevelopersBuilder(
        int index) {
      return getDevelopersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public com.test.proto.DeveloperOrBuilder getDevelopersOrBuilder(
        int index) {
      if (developersBuilder_ == null) {
        return developers_.get(index);  } else {
        return developersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public java.util.List<? extends com.test.proto.DeveloperOrBuilder> 
         getDevelopersOrBuilderList() {
      if (developersBuilder_ != null) {
        return developersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(developers_);
      }
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public com.test.proto.Developer.Builder addDevelopersBuilder() {
      return getDevelopersFieldBuilder().addBuilder(
          com.test.proto.Developer.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public com.test.proto.Developer.Builder addDevelopersBuilder(
        int index) {
      return getDevelopersFieldBuilder().addBuilder(
          index, com.test.proto.Developer.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.proto.Developer developers = 3;</code>
     */
    public java.util.List<com.test.proto.Developer.Builder> 
         getDevelopersBuilderList() {
      return getDevelopersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.proto.Developer, com.test.proto.Developer.Builder, com.test.proto.DeveloperOrBuilder> 
        getDevelopersFieldBuilder() {
      if (developersBuilder_ == null) {
        developersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.proto.Developer, com.test.proto.Developer.Builder, com.test.proto.DeveloperOrBuilder>(
                developers_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        developers_ = null;
      }
      return developersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.test.proto.Software)
  }

  // @@protoc_insertion_point(class_scope:com.test.proto.Software)
  private static final com.test.proto.Software DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.proto.Software();
  }

  public static com.test.proto.Software getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Software>
      PARSER = new com.google.protobuf.AbstractParser<Software>() {
    public Software parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Software(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Software> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Software> getParserForType() {
    return PARSER;
  }

  public com.test.proto.Software getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

