// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: software.proto

package com.test.proto;

public interface SoftwareListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.proto.SoftwareList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  java.util.List<com.test.proto.Software> 
      getSoftwaresList();
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  com.test.proto.Software getSoftwares(int index);
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  int getSoftwaresCount();
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  java.util.List<? extends com.test.proto.SoftwareOrBuilder> 
      getSoftwaresOrBuilderList();
  /**
   * <code>repeated .com.test.proto.Software softwares = 1;</code>
   */
  com.test.proto.SoftwareOrBuilder getSoftwaresOrBuilder(
      int index);
}
