// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: software.proto

package com.test.proto;

public interface SoftwareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.proto.Software)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  java.util.List<com.test.proto.Developer> 
      getDevelopersList();
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  com.test.proto.Developer getDevelopers(int index);
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  int getDevelopersCount();
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  java.util.List<? extends com.test.proto.DeveloperOrBuilder> 
      getDevelopersOrBuilderList();
  /**
   * <code>repeated .com.test.proto.Developer developers = 3;</code>
   */
  com.test.proto.DeveloperOrBuilder getDevelopersOrBuilder(
      int index);
}
